### ISSUE TITLE
[To-Do] Support socket communication 📡

### ISSUE THREAD

**Issue by Oriburger** [Oriburger/cli_bubble_pop#1]
## To-Do list

- [x]  Add socket communication base

- [x] Support multi-thread based multiple-client 

- [x] Support data 2nd dimensional array in recv() & send()
