### ISSUE TITLE
[To-Do] OOP 기법 적용 외

### ISSUE THREAD

**Issue by Oriburger** [Oriburger/cli_bubble_pop#3]
- [ ] 정보은닉, 캡슐화 등 OOP 기법  적용
- [ ] 구조체 <-> 클래스 전환 및 클래스 문법 적용
- [ ] Modern c++  적용

**Comment by Oriburger** [comment]
- [x] Doxygen 스타일 주석 적용
